apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-167847401
  namespace: gpynjnmb-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/build_service@sha256:5c29cb8a67ae81d1ed646c90fbae782a75772d33761f2077bc878b022255fc02
        name: my-java-quarkus
        resources: {}
status: {}
