apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-167847401
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-167847401
    app.kubernetes.io/part-of: test-app-167847401
  name: java-quarkus-167847401
  namespace: gpynjnmb-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-167847401
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-167847401
    spec:
      containers:
      - image: quay.io/hacdev/build_service@sha256:5c29cb8a67ae81d1ed646c90fbae782a75772d33761f2077bc878b022255fc02
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
